apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot_ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: springboot-ui
  template:
    metadata:
      labels:
        app: springboot-ui
    spec:
      containers:
      - image: docker.io/manufacturingbigdata/spring-demo
        name: springboot-ui
        ports:
        - containerPort: 8080
