apiVersion: v1
kind: Service
metadata:
  name: hello-spring
  namespace : springdemo
spec:
  type: NodePort
  selector:
    app: hello-spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  #externalName: hello-spring.springdemo.svc.cluster.local
